### ISSUE TITLE
Rails 7.0.3 - Webpacker configuration file not found when running `rails webpacker:install` (shakapacker v6.3)

### ISSUE THREAD

**Issue by jasonfb** [shakacode/shakapacker#123]
Ruby version: 3.1.2
Rails version: 7.0.3
Shakapacker version: 6.3.0

Steps to reproduce:
`rails new HelloShakapaker1 --skip-javascript --database=postgresql`
`bundle add shakapacker --strict`
`rails webpacker:install`

for some reason I seem to have something missed here, this task tells me `No such file or directory config/webpacker.yml` but as far as I understand this command should create this for me no? Maybe this is a Rails 7 thing or perhaps I missed something?

example app  is here
https://github.com/jasonfb/HelloShakapakerRails7C

thank you!
```
% rails webpacker:install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
/Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/jason/.rvm/gems/ruby-2.7.2/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/jason/.rvm/gems/ruby-2.7.2/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/Users/jason/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/jason/.rvm/gems/ruby-2.7.2/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
rails aborted!
Webpacker configuration file not found /Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_check_realpath_internal - /Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C/config/webpacker.yml
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:112:in `rescue in load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:101:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:98:in `data'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:93:in `fetch'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:33:in `webpacker_precompile?'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/tasks/webpacker/clean.rake:14:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/application.rb:505:in `block in run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine/railties.rb:15:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine/railties.rb:15:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/application.rb:505:in `run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:464:in `load_tasks'
/Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C/Rakefile:6:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/command.rb:51:in `invoke'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C/config/webpacker.yml
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/compile_cache/yaml.rb:313:in `realpath'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/compile_cache/yaml.rb:313:in `load_file'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:105:in `rescue in load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:102:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:98:in `data'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:93:in `fetch'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:33:in `webpacker_precompile?'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/tasks/webpacker/clean.rake:14:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/application.rb:505:in `block in run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine/railties.rb:15:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine/railties.rb:15:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/application.rb:505:in `run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:464:in `load_tasks'
/Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C/Rakefile:6:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/command.rb:51:in `invoke'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

Caused by:
ArgumentError: unknown keyword: :aliases
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/compile_cache/yaml.rb:307:in `load_file'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:103:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:98:in `data'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:93:in `fetch'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/webpacker/configuration.rb:33:in `webpacker_precompile?'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/shakapacker-6.3.0/lib/tasks/webpacker/clean.rake:14:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `block in run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:661:in `run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/application.rb:505:in `block in run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine/railties.rb:15:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine/railties.rb:15:in `each'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/application.rb:505:in `run_tasks_blocks'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/engine.rb:464:in `load_tasks'
/Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C/Rakefile:6:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/command.rb:51:in `invoke'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/jason/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
jason@MBA22 /Users/jason/Work/_LEARNING/ReactOnRails/HelloShakapakerRails7C [main]
% 
```

5♠︎

**Comment by Stex** [comment]
A workaround that worked until this is fixed:

* install the last version (6.2.1)
* run `bin/rails webpacker:install`
* upgrade to `6.3`
* run `bin/rails webpacker:install` again and override the files

**Comment by tomdracz** [comment]
Thanks for reporting.  Another workaround is get the file at https://github.com/shakacode/shakapacker/blob/master/lib/install/config/webpacker.yml and copy over to `config/webpacker.yml` before running the install task.

I think this got introduced by https://github.com/shakacode/shakapacker/pull/102/files CC @Judahmeek @justin808 

We're referencing `Webpacker.config` in few tasks after the PR above so for the new app, Rails crashes when trying to load those tasks.

We do have a catch at https://github.com/shakacode/shakapacker/blob/master/lib/webpacker/configuration.rb#L109 but it doesn't seem like it's being picked up in this scenario.

**Comment by jasonfb** [comment]
rails new HelloShakapaker1 --skip-javascript --database=postgresql

bundle add shakapacker --strict

fix shakapacker version to 

`gem "shakapacker", "= 6.2.1"`

then run 
`bin/rails webpacker:install`


then update shakapacker back to 6.3 in Gemfile

**Comment by tomdracz** [comment]
@jasonfb Reopening to keep track of this. Glad we have workarounds but it needs to be properly fixed!

**Comment by difernandez** [comment]
Posting this in case it's relevant: ran into this issue just now and I found [this similar issue on the webpacker repo](https://github.com/rails/webpacker/pull/3223), with a PR in the end that appears to have fixed it

**Comment by justin808** [comment]
Shipped!
